# Generated by Django 2.0.1 on 2018-02-21 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('display_id', models.IntegerField(primary_key=True, serialize=False)),
                ('display', models.CharField(max_length=300)),
                ('client_address', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('widget_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.Widget'),
        ),
    ]
