# Generated by Django 2.0.1 on 2018-02-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='name',
            field=models.CharField(default='text', max_length=120),
        ),
    ]
