# Generated by Django 2.0.1 on 2018-02-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('widget_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.Widget'),
        ),
    ]
