# Generated by Django 2.0.1 on 2018-02-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_datetime_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_datetime_min',
            field=models.IntegerField(null=True),
        ),
    ]
