# Generated by Django 2.0.1 on 2018-02-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_auto_20180221_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=700)),
                ('task_datetime_hour', models.IntegerField(null=True)),
                ('task_datetime_min', models.IntegerField(null=True)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.Widget')),
            ],
        ),
    ]
