# Generated by Django 2.0.1 on 2018-02-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_taskschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='task_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
