# Generated by Django 2.0.1 on 2018-02-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0007_task_task_week_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='task_week_day',
            field=models.IntegerField(null=True),
        ),
    ]
