# Generated by Django 2.0.1 on 2018-03-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0008_taskschedule_task_week_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTimeSlice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
