# Generated by Django 2.0.1 on 2018-03-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0009_classtimeslice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtimeslice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
