# Generated by Django 2.0.1 on 2018-04-22 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0011_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('subject_name', models.CharField(max_length=400)),
                ('week_day', models.IntegerField()),
                ('start_time_min', models.IntegerField()),
                ('start_time_hour', models.IntegerField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.ClassRoom')),
            ],
        ),
    ]
