# Generated by Django 2.0.1 on 2018-04-23 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0012_classroomschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='subject_name_widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_name_widget', to='integration.Widget'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher_name_widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_name_widget', to='integration.Widget'),
        ),
    ]
