# Generated by Django 2.0.1 on 2018-05-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0014_tempmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempModel',
        ),
    ]
