# Generated by Django 2.0.1 on 2018-05-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0015_delete_tempmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassTimeSlice',
        ),
        migrations.RemoveField(
            model_name='task',
            name='widget',
        ),
        migrations.RemoveField(
            model_name='taskschedule',
            name='widget',
        ),
        migrations.AddField(
            model_name='display',
            name='alias',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskSchedule',
        ),
    ]
