# Generated by Django 2.0.1 on 2018-05-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0016_auto_20180529_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='alias',
            field=models.CharField(default='Room', max_length=300, null=True),
        ),
    ]
