# Generated by Django 2.0.1 on 2018-05-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0017_auto_20180529_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='is_in_hallway',
            field=models.NullBooleanField(default=False),
        ),
    ]
