# Generated by Django 2.0.1 on 2018-05-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0019_hallwaypropagationthesisschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallwaypropagationthesisschedule',
            name='place',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
